La estructura central de Numnar es el Array.
Además represanta datos de manera más estructurada, 
Acceso a uno o muchos más elementos.

In [ ]:
import numpy as np

    Así importamos la librería de numpy en Python

Para importar una lista a numpy:

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Para llevar una lista a un objeto Array de numpy, escribimos el siguente comando:

In [4]:
np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.array(lista)

In [7]:
type(arr)

numpy.ndarray

    Además de crear objetos de tipo lista (con una sola dimensión), podemos crear una matriz:

In [8]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Para utilziar el Indexado, jugamos con las posiciónes dentro de los array:

In [10]:
arr
#Entre corchetes va la posición
arr[1]

2

    Podemos sumar el index de los array

In [11]:
arr[0] + arr[5]

7

También podemos hacer la indexación para las matrices:

In [13]:
matriz[0]

array([1, 2, 3])

In [14]:
matriz[0,2]

3

    Podemos recorrer los array:

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos recorrer los arrya con [], en donde podemos indicar el inicio con el indice, separado con :, podemos indicar el fin hasta donde queremos recorrer

In [16]:
arr[1:6]

array([2, 3, 4, 5, 6])

Cuando no indicamos el index de inicio, automáticamente, recorrerá el array desde la prosición 0

In [17]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

De igual forma, cuando no definimos el index final, recorrerá el array hasta la ultima posición.

In [18]:
arr[6:]

array([7, 8, 9])

También podemos recorrer el array de forma completa cuando no especificamos un inicio y un fin

In [19]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora, para recorrer una array de forma presonalizada, podemos indicar, despues de establecer un inicio y un fin, con otros :, y la secuencia que queramos que recorrá el arreglo

In [21]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#En esta caso, recorrerá el array de 2 en 2 posiciones
arr[::2]

array([1, 3, 5, 7, 9])

In [ ]:
#En esta caso, recorrerá el array de 3 en 3 posiciones
arr[::3]

    Podemos recorrer de igual forma las matrices

In [22]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])